helm 2.11
I recently updated my channel, which upgraded helm from 2.11 to 2.14.
But the odeko clusters are running 2.12, which is not compatible with
2.14, leading to errors like the following:

  Error: incompatible versions client[v2.14.2] server[v2.12.3]
  Error: UPGRADE FAILED: incompatible versions client[v2.14.2] server[v2.12.3]

Grab 2.11 from an older revision of nixpkgs.